### ISSUE TITLE
there is a problem with the "MediaPlayer" module

### ISSUE THREAD

**Issue by florianpetiot** [ree1261/pyvidplayer#1]
in  pyvidplayer.py
line 3:
from ffpyplayer.player import MediaPlayer

ImportError: DLL load failed while importing player: The specified module cannot be found.

How can I fix this error?

**Comment by anrayliu** [comment]
ffpyplayer isn't installed properly. try reinstalling it, and make sure it works by itself

**Comment by florianpetiot** [comment]
I reinstalled it properly using the `--no-cache-dir` command to re-download it and it doesn't work any better.

This is strange because if you watch this video https://youtu.be/Xu8SLkvFq8I :
at 2:49 you can see that 'MediaPlayer' is not written in yellow like the other imports (I have the same case)
but it still works for him

I think I'll look for another solution 😥

**Comment by anrayliu** [comment]
Huh. That's strange. Try installing it through pip.

If you're looking for ways to play videos in Python, you're in luck because I literally spent dozens of hours trying different ways. Besides my module, you're next best bet is to use cv2 and mini_audio. You can check out my repo "rune" to see how it works. It'll use more cpu and have to extract the audio from the video, but it works well. Moviepy is very heavy and don't recommend. VLC doesn't work with Pygame and crashes with mkv files. Pyglet's internal clock for video playback is busted, and it's seeking when playing audio is also broken.

Well if you have any questions, just ask.

**Comment by florianpetiot** [comment]
Yes, I installed it with `pip install ffpyplayer --no-cache-dir`, because otherwise it used a cached file to reload it

Actually I'm looking to display two videos with specific coordinates and size in my game's window

Thank you for all this information, I will continue my research
Merci beaucoup ! 😀
