### ISSUE TITLE
Resize video not working

### ISSUE THREAD

**Issue by damiandrake0** [ree1261/pyvidplayer#11]
Hi, how do I resize a video?
How to use alt_resize?
Thank you in advance,
happy Christmas holidays!

**Comment by anrayliu** [comment]
Hello,

video.set_size((1280, 720)) will set the size of the video. However, this
uses ffpyplayer's resizing method, which doesn't seem to always work. As a
backup, I added an alt_resize in case it fails. alt_resize is an attribute
of the video, and it holds a callable. When every video frame is rendered,
it'll make a check to see if the size is correct. If not, alt_resize() will
be applied. By default, I believe alt_resize is
pygame.transform.smoothscale. If you call set_size and alt_resize is the
default value, but the video is still not properly resized, that must be a
bug and I can take a deeper look.

Good luck!

**Comment by damiandrake0** [comment]
Hi @ree1261,
alt_resize still doesn't work for me, instead set_size works very well.
Thank you very much!

**Comment by anrayliu** [comment]
That's great to hear. alt_resize by itself doesn't do anything. It's
already being called automatically if needed. The only disadvantage to the
alt_resize is higher cpu usage. Anyway let me know if you need help with
anything else.

**Comment by damiandrake0** [comment]
Wait, so for alt_resize to work what is needed in the code? Send me sample code that uses alt_resize, thank you again!

**Comment by anrayliu** [comment]
Pyvidplayer works by using ffpyplayer to read video frames, and then it converts those frames into a pygame surface. Set_size will tell ffpyplayer to resize the video frames, but this is sometimes bugged. Remember, alt_resize is a function that resizes pygame surfaces. Every frame, the rendered pygame surface will be checked to see if it's in the right size. If it's not, alt_resize will be called to correct the pygame surface.

So to use pyvidplayer, all you have to do is call set_size. Nothing else. alt_resize defaults to pygame.transform.smoothscale and will be called automatically when needed.

When you call set_size, 2 things can happen.

1, ffpyplayer properly resizes the video. You get low cpu usage and good quality images

2, ffpyplayer fails to resize the video. In this case, alt_resize will automatically correct the size. Cpu usage is higher, but you retain video quality. This is where someone might want to change alt_resize. By putting `video.alt_resize = pygame.transform.scale` after set_size, you can sacrifice video quality for less cpu usage during scenario 2s

From my findings, scenario 2 seems to happen randomly. The problem lies within ffpyplayer, not pyvidplayer.

Just remember, you only need to worry about alt_resize if scenario 2 happens AND you care about higher cpu usage. Otherwise, it's negligible. 

Anyways hopefully this clears things up

**Comment by damiandrake0** [comment]
Now all very clear, thank you. Now I can integrate pyvidplayer into my Pygame project ;)
